# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a02b6a9043c28d7a7549ebc32d0395248a7c1061bef994aed87964cb46d1b5ef619cff82e48084e315a87a2838ca2d7b3aa4af11c22a069a2cb075b8f3078895

test:
  secret_key_base: 7014e63b99a72b20741d00eafc0bf4e6a1d52e1c59e0c7e106a5c538b727d4c6502bfe655114f977b4097cbce55b112e7477aa0652ee4d9e0c51bb3dc9d417b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
